//+------------------------------------------------------------------+
//| Tick_Reversion_Pro.mq5                                            |
//| Example MT5 EA based on tick mean reversion ideas                 |
//| Generated by ChatGPT                                              |
//| No guarantee of profitability or win rate                         |
//+------------------------------------------------------------------+
#property strict
#include <Trade/Trade.mqh>

input double ForexLotSize=0.10;
input double OtherLotSize=0.01;
input int LookbackTicks=50;
input double DeviationThreshold=1.5;
input int ATRPeriod=14;
input double ATRMultiplier=2.5;
input double RiskReward=4.0;
input int MaxPositionsPerSymbol=2;
input bool UseEMA200=true;
input double ProfitTargetPerLot=100.0;
input ulong MagicNumber=777777;

double TickBuffer[];
int atrHandle;
int emaHandle;
CTrade trade;

double GetLotSize()
{
   string s=_Symbol;

   if(StringFind(s,"XAU")>=0 || StringFind(s,"XAG")>=0 ||
      StringFind(s,"BTC")>=0 || StringFind(s,"ETH")>=0 ||
      StringFind(s,"US30")>=0 || StringFind(s,"NAS")>=0 ||
      StringFind(s,"GER")>=0)
      return OtherLotSize;

   return ForexLotSize;
}

int CountPositionsForSymbol()
{
   int count=0;

   for(int i=PositionsTotal()-1;i>=0;i--)
   {
      ulong ticket=PositionGetTicket(i);

      if(!PositionSelectByTicket(ticket))
         continue;

      if(PositionGetInteger(POSITION_MAGIC)!=MagicNumber)
         continue;

      if(PositionGetString(POSITION_SYMBOL)!=_Symbol)
         continue;

      count++;
   }

   return count;
}

bool TrendFilter(ENUM_ORDER_TYPE type)
{
   if(!UseEMA200)
      return true;

   double ema[1];

   if(CopyBuffer(emaHandle,0,1,1,ema)<1)
      return false;

   double close=iClose(_Symbol,_Period,1);

   if(type==ORDER_TYPE_BUY)
      return close>ema[0];

   return close<ema[0];
}

double DynamicStopDistance()
{
   double atr[1];

   if(CopyBuffer(atrHandle,0,0,1,atr)<1)
      return 100*_Point;

   double stopLevel=SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL)*_Point;
   double freezeLevel=SymbolInfoInteger(_Symbol,SYMBOL_TRADE_FREEZE_LEVEL)*_Point;
   double spread=SymbolInfoDouble(_Symbol,SYMBOL_ASK)-SymbolInfoDouble(_Symbol,SYMBOL_BID);

   double brokerMin=MathMax(MathMax(stopLevel,freezeLevel),spread*10.0);

   return MathMax(atr[0]*ATRMultiplier,brokerMin*3.0);
}

void ManageProfitTarget()
{
   for(int i=PositionsTotal()-1;i>=0;i--)
   {
      ulong ticket=PositionGetTicket(i);

      if(!PositionSelectByTicket(ticket))
         continue;

      if(PositionGetInteger(POSITION_MAGIC)!=MagicNumber)
         continue;

      if(PositionGetString(POSITION_SYMBOL)!=_Symbol)
         continue;

      double profit=PositionGetDouble(POSITION_PROFIT);
      double volume=PositionGetDouble(POSITION_VOLUME);

      if(profit>=volume*ProfitTargetPerLot)
         trade.PositionClose(ticket);
   }
}

void ManageTrailing()
{
   double dist=DynamicStopDistance();

   for(int i=PositionsTotal()-1;i>=0;i--)
   {
      ulong ticket=PositionGetTicket(i);

      if(!PositionSelectByTicket(ticket))
         continue;

      if(PositionGetInteger(POSITION_MAGIC)!=MagicNumber)
         continue;

      if(PositionGetString(POSITION_SYMBOL)!=_Symbol)
         continue;

      ENUM_POSITION_TYPE pos=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);

      double sl=PositionGetDouble(POSITION_SL);
      double tp=PositionGetDouble(POSITION_TP);

      double bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);
      double ask=SymbolInfoDouble(_Symbol,SYMBOL_ASK);

      if(pos==POSITION_TYPE_BUY)
      {
         double newSL=NormalizeDouble(bid-dist,_Digits);

         if(newSL>sl)
            trade.PositionModify(ticket,newSL,tp);
      }
      else
      {
         double newSL=NormalizeDouble(ask+dist,_Digits);

         if(sl==0 || newSL<sl)
            trade.PositionModify(ticket,newSL,tp);
      }
   }
}

void ExecuteDeal(ENUM_ORDER_TYPE type)
{
   double dist=DynamicStopDistance();

   double price=(type==ORDER_TYPE_BUY)
      ? SymbolInfoDouble(_Symbol,SYMBOL_ASK)
      : SymbolInfoDouble(_Symbol,SYMBOL_BID);

   double sl=(type==ORDER_TYPE_BUY) ? price-dist : price+dist;
   double tp=(type==ORDER_TYPE_BUY) ? price+dist*RiskReward : price-dist*RiskReward;

   trade.PositionOpen(
      _Symbol,
      type,
      GetLotSize(),
      price,
      NormalizeDouble(sl,_Digits),
      NormalizeDouble(tp,_Digits),
      "TickReversionPro"
   );
}

int OnInit()
{
   ArrayResize(TickBuffer,LookbackTicks);
   ArrayInitialize(TickBuffer,0);

   atrHandle=iATR(_Symbol,_Period,ATRPeriod);
   emaHandle=iMA(_Symbol,_Period,200,0,MODE_EMA,PRICE_CLOSE);

   trade.SetExpertMagicNumber(MagicNumber);

   return(INIT_SUCCEEDED);
}

void OnTick()
{
   double bid=SymbolInfoDouble(_Symbol,SYMBOL_BID);

   for(int i=LookbackTicks-1;i>0;i--)
      TickBuffer[i]=TickBuffer[i-1];

   TickBuffer[0]=bid;

   ManageProfitTarget();
   ManageTrailing();

   if(TickBuffer[LookbackTicks-1]==0)
      return;

   if(CountPositionsForSymbol()>=MaxPositionsPerSymbol)
      return;

   double sum=0;

   for(int i=0;i<LookbackTicks;i++)
      sum+=TickBuffer[i];

   double avg=sum/LookbackTicks;

   double var=0;

   for(int i=0;i<LookbackTicks;i++)
      var+=MathPow(TickBuffer[i]-avg,2);

   double sd=MathSqrt(var/LookbackTicks);

   if(sd<=0)
      return;

   double z=(bid-avg)/sd;

   if(z<=-DeviationThreshold && TrendFilter(ORDER_TYPE_BUY))
      ExecuteDeal(ORDER_TYPE_BUY);

   if(z>=DeviationThreshold && TrendFilter(ORDER_TYPE_SELL))
      ExecuteDeal(ORDER_TYPE_SELL);
}
